### PR TITLE
Add `tracking` property to sliders.  When False, changed only emits on release.

### PR DESCRIPTION
**Pull request by tlambert03**
closes #https://github.com/napari/magicgui/issues/234

This adds a 'tracking' property to sliders, following the [naming set by Qt](https://doc.qt.io/qt-5/qabstractslider.html#tracking-prop):

> ### tracking : **bool**
> This property holds whether slider tracking is enabled
>
> ----------
>If tracking is enabled (the default), the slider emits the valueChanged() signal while the slider is being dragged. If tracking is disabled, the slider emits the valueChanged() signal only when the user releases the slider.

```py
from magicgui import magicgui


@magicgui(auto_call=True, input={"widget_type": "Slider", "tracking": False})
def slider(input=1):
    ...
```

### CODE REVIEW

**Comment by queenmatalie** [comment]
can i used used example ( the clock deblur example using napari & magicgui:) with real time.

**Comment by tlambert03** [comment]
I'm sorry, I'm not following... clarify?

**Comment by queenmatalie** [comment]
Can  used napari to display a video?

**Comment by queenmatalie** [comment]
code clock deblur example using napari & magicgui:
can not run this code 

AttributeError: No napari attribute types

**Comment by tlambert03** [comment]
Hi @queenmatalie, I'm sorry, I don't understand.  If you'd like help running the example, you'll need to provide more information.  What version of napari and magicgui are you running, exactly what code are you running, etc...

**Comment by queenmatalie** [comment]
Python 3.8.8 on windows 10 used this code on jupyter notebook 
when command version napari on anaconda this result below:
'napari--version' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tlambert03** [comment]
you can't run the command `napari` in a jupyter notebook.  it's a command line command.  please have a look through the napari tutorials for an introduction to napari
https://napari.org/tutorials/fundamentals/index.html

**Comment by queenmatalie** [comment]
thank you , very much

**Pull request merged**
