### PR TITLE
Fix bug in creation of RangeEdit using create_widget

### PR DESCRIPTION
**Pull request by Czaki**
When run this code 

```python
from magicgui.widgets import create_widget

w = create_widget(annotation=range)
```
it ends with error:
```
Traceback (most recent call last):
  File "/home/czaki/Projekty/neutrofile/Tutorial/sample_magicgui.py", line 3, in <module>
    w = create_widget(annotation=range)
  File "/home/czaki/.pyenv/versions/3.8.3/envs/neutrofile/lib/python3.8/site-packages/magicgui/widgets/_bases/create_widget.py", line 96, in create_widget
    widget = wdg_class(**kwargs)
  File "/home/czaki/.pyenv/versions/3.8.3/envs/neutrofile/lib/python3.8/site-packages/magicgui/widgets/_concrete.py", line 558, in __init__
    raise TypeError(f"Invalid value type for {type(self)}: {type(value)}")
TypeError: Invalid value type for <class 'magicgui.widgets.RangeEdit'>: <class 'magicgui.widgets._bases.value_widget._Unset'>
```

When fixing this error by checking if `value` is `None` or `UNSET` then also happens problem with an unexpected `nullable` field.
The second error I fix  by `pop` the `nullable` from kwargs. But I'm not sure if it is the correct solution.

### CODE REVIEW

**Comment by tlambert03** [comment]
thanks @Czaki!  These changes make sense / work for me.  more broadly, I think the issue here stems from having these "container-based" classes that more or less implement the `ValueWidget` protocol, but don't directly inherit from valuewidget.  (see https://github.com/napari/magicgui/issues/372).

This change is totally fine with me as a first step... maybe in the future, I can get around to making them actually be `ValueWidgets` (in which case `nullable` should work again, and allow things like `create_widget(annotation=Optional[range])`

**Review by tlambert03 — APPROVED** [review]

**Comment by tlambert03** [comment]
This came up before in some issue, can't find it atm, since not all widgets are necessarily value widgets, I'm not sure that's the proper annotation?

**Comment by Czaki** [comment]
Hm. In general I know because Container is also widget. But what input to `create_widget` could create non-value widget?

Or you think about user registered widget?

**Comment by tlambert03** [comment]
> But what input to create_widget could create non-value widget?

Yeah, _thats_ a good question :)

I can't immediately think of one.  I'm open to it.  I remember trying to change it one point and then realizing that changing that annotation requires a lot of other type changes elsewhere, but it might be worth it.  Feel free to dig a bit deeper if you're interested

**Comment by Czaki** [comment]
If I should fix somehow failing test? It looks non-related.

**Pull request merged**
